package Lab10;
import java.awt.*;

import simView.*;

public class LRBSM extends ViewableDigraph
{
	final int NODE = 4;
	protected int [] proc_t = {0, 25, 15, 50, 25};
	protected int [] q_size = {0, 2, 3, 4, 5};
	public LRBSM()
	{
		super("LRBSM");
    	
		ViewableAtomic g = new genr("genr", 3);
		ViewableAtomic s = new scheduler("scheduler", 0, NODE, q_size);
		ViewableAtomic t = new transd("transd", 3000, NODE);
    	
		add(g);
		add(s);
		add(t);
  
		addCoupling(g, "out", s, "in");
		addCoupling(g, "out", t, "ariv");
		addCoupling(t, "out", g, "in");
		
		addCoupling(s, "out_loss", t, "loss");
		
		for(int i = 1; i <= NODE; i++) {
			ViewableAtomic p = new processor("processor" + i, proc_t[i], q_size[i]);
			add(p);
			addCoupling(p, "out", s, "in"+i);
			addCoupling(p, "out", t, "solved");
			addCoupling(s, "out"+i, p, "in");
		}
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("processor2")).setPreferredLocation(new Point(468, 48));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(743, 459));
        ((ViewableComponent)withName("transd")).setPreferredLocation(new Point(673, 283));
        ((ViewableComponent)withName("processor1")).setPreferredLocation(new Point(244, 61));
        ((ViewableComponent)withName("processor4")).setPreferredLocation(new Point(258, 458));
        ((ViewableComponent)withName("processor3")).setPreferredLocation(new Point(204, 335));
        ((ViewableComponent)withName("scheduler")).setPreferredLocation(new Point(438, 260));
    }
}
