package midterm_1;
import java.awt.*;

import simView.*;

public class gpt extends ViewableDigraph
{

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("g", 10);
		ViewableAtomic p = new procQ("p", 10);
    	
		add(g);
		add(p);
  
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 651);
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(393, 254));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(96, 143));
    }
}
