package Lab08;
import java.awt.*;
import simView.*;

public class add_function extends ViewableDigraph
{

	public add_function()
	{
		super("add_function");
    	
		ViewableAtomic g = new user("g", 10);
		ViewableAtomic p = new add("p", 10);
    	
		add(g);
		add(p);
  
		addCoupling(g, "out", p, "in");

		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(908, 482);
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(562, 112));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(150, 285));
    }
}
