package Lab09_HW;
import java.awt.*;

import simView.*;

public class RRSM extends ViewableDigraph
{
	final int NODE = 6;
	final int QUEUE = 2;
	
	
	public RRSM()
	{
		super("RRSM");
    	
		ViewableAtomic g = new genr("genr", 40);
		ViewableAtomic s = new scheduler("scheduler", 0, NODE);
		ViewableAtomic t = new transd("transd", 4500, NODE);
    	
		add(g);
		add(s);
		add(t);
  
		addCoupling(g, "out", s, "in");
		addCoupling(g, "out", t, "ariv");     
		addCoupling(t, "out", g, "in");
		
		for(int i=1; i<=NODE; i++) {
			ViewableAtomic p = new processor("processor" + i, 100+(20*i), QUEUE);
			add(p);
			
			addCoupling(p, "out1", t, "solved");
			addCoupling(p, "out2", t, "loss");     
			addCoupling(s, "out"+i, p, "in");
		}
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("processor4")).setPreferredLocation(new Point(464, 367));
        ((ViewableComponent)withName("processor5")).setPreferredLocation(new Point(464, 437));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(43, 301));
        ((ViewableComponent)withName("processor3")).setPreferredLocation(new Point(469, 251));
        ((ViewableComponent)withName("scheduler")).setPreferredLocation(new Point(191, 183));
        ((ViewableComponent)withName("processor1")).setPreferredLocation(new Point(467, 93));
        ((ViewableComponent)withName("processor2")).setPreferredLocation(new Point(469, 172));
        ((ViewableComponent)withName("processor6")).setPreferredLocation(new Point(465, 514));
        ((ViewableComponent)withName("transd")).setPreferredLocation(new Point(738, 307));
    }
}
