package Lab03;
import java.awt.*;
import simView.*;

public class gproc extends ViewableDigraph
{

	public gproc()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("g", 30);
		ViewableAtomic p = new proc("p", 45);
    	
		add(g);
		add(p);
  
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(371, 345));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(59, 148));
    }
}
