package finalexam;
import simView.*;



import java.awt.*;


public class ef extends ViewableDigraph
{
	
	public ef()
	{
		this("site", 20, 20);
	}
	
	public ef(String name, double int_arr_t, double observe_t)
	{
		super(name);
		
		addInport("in"); 
		addOutport("out");
		
		ViewableAtomic r = new proc_reserve("reserve", int_arr_t);
		ViewableAtomic c = new proc_cancel("cancel", observe_t);

		add(r);
		add(c);

		addCoupling(this, "in", c, "in");
		addCoupling(this, "in", r, "in");

		addCoupling(c, "out", this, "out");
		addCoupling(r, "out", this, "out");
		
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(463, 297);
        ((ViewableComponent)withName("reserve")).setPreferredLocation(new Point(60, 87));
        ((ViewableComponent)withName("cancel")).setPreferredLocation(new Point(60, 179));
    }
}
