package finalexam;
import java.awt.*;



import simView.*;

public class efp extends ViewableDigraph 
{

	public efp()
	{
		super("efp");
		
		ViewableAtomic g = new genr("genr", 70);
		ViewableDigraph expf = new ef("site", 20, 20);
		ViewableAtomic m = new proc_meal("meal", 20);
		ViewableAtomic c = new proc_check("check", 10);
		
		add(expf);
		add(g);
		add(m);
		add(c);

		addCoupling(g, "out", expf, "in");
		addCoupling(expf, "out", m, "in");
		addCoupling(g, "check", c, "in");
		addCoupling(m, "out", c, "in");
		addCoupling(c, "out", g, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("meal")).setPreferredLocation(new Point(638, 441));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(36, 132));
        ((ViewableComponent)withName("site")).setPreferredLocation(new Point(179, 263));
        ((ViewableComponent)withName("check")).setPreferredLocation(new Point(772, 268));
    }
 }
