package midterm;
import java.awt.Dimension;


import java.awt.Point;

import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

public class efp extends ViewableDigraph 
{

	public efp()
	{
		super("efp");
		
		ViewableAtomic sp = new genr("genr", 30);
		ViewableDigraph  expf = new ef("ExpFrame", 10, 10);

		add(expf);
		add(sp);

		addCoupling(expf, "prob_out", sp, "in");

		addCoupling(sp, "out", expf, "prob_in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(36, 240));
        ((ViewableComponent)withName("ExpFrame")).setPreferredLocation(new Point(259, 93));
    }
 }
